// Jenkins CI/CD pipeline for the TechnoVista college-event-website project.
//
// Scope: CI build + Docker smoke test (Phase 5B) + Kubernetes deployment (Phase 6B).
//   - Clones the repo, verifies the toolchain, runs the Maven build,
//     builds a Docker image, verifies both build outputs, and archives
//     the build artifacts.
//   - Runs the built image in a throwaway container on port 8082,
//     curls it to confirm the site is actually served, then always
//     tears the container down (post { always {} }), even if the
//     smoke test fails.
//   - After the smoke test passes, tags the image with the build
//     number, applies the existing k8s/ manifests, points the live
//     Deployment at that versioned tag, and waits for the rollout to
//     succeed before continuing.
//   - Does NOT push images to a registry, or touch monitoring
//     (Nagios/Grafana/Graphite/Prometheus). Those belong to later phases.
//
// Agent: Windows Jenkins agent (uses `bat`, not `sh`).

pipeline {
    agent any

    options {
        timestamps()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Source') {
            steps {
                // Public repository - no Jenkins credentials required.
                git branch: 'main', url: 'https://github.com/bk9571/college-event-website.git'
            }
        }

        stage('Environment Verification') {
            steps {
                bat 'git --version'
                bat 'java -version'
                bat 'mvn -version'
                bat 'docker version'
            }
        }

        stage('Maven Build') {
            steps {
                // Fails the pipeline immediately if the Maven build fails.
                bat 'mvn clean package'
            }
        }

        stage('Verify Build Output') {
            steps {
                bat '''
                    if not exist "target\\site" (
                        echo ERROR: target\\site was not generated by the Maven build.
                        exit /b 1
                    )
                    echo target\\site verified.
                '''
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t college-event-website:latest .'
            }
        }

        stage('Verify Docker Image') {
            steps {
                bat '''
                    docker image inspect college-event-website:latest >nul 2>&1
                    if errorlevel 1 (
                        echo ERROR: Docker image college-event-website:latest was not found.
                        exit /b 1
                    )
                    echo Docker image college-event-website:latest verified.
                '''
            }
        }

        stage('Run Docker Container') {
            steps {
                // Remove any leftover container from a previous run; ignore errors if it doesn't exist.
                bat '''
                    docker stop college-event-ci
                    docker rm college-event-ci
                    exit /b 0
                '''
                bat '''
                    docker run -d ^
                        --name college-event-ci ^
                        -p 8082:80 ^
                        college-event-website:latest
                '''
                // Give nginx a moment to start before the smoke test hits it.
                // (Using ping instead of timeout - timeout fails on non-interactive Jenkins agents.)
                bat 'ping -n 6 127.0.0.1 >nul'
            }
        }

        stage('Smoke Test') {
            steps {
                bat '''
                    curl -f -s -o smoke_test_response.html http://localhost:8082/
                    if errorlevel 1 (
                        echo ERROR: Smoke test failed - website did not respond on http://localhost:8082/
                        exit /b 1
                    )

                    findstr /C:"TechnoVista" smoke_test_response.html >nul
                    if errorlevel 1 (
                        echo ERROR: Smoke test failed - response did not contain expected content "TechnoVista"
                        exit /b 1
                    )

                    echo Smoke test passed: website responded on port 8082 and contains expected content.
                '''
            }
        }

        stage('Tag Docker Image') {
    steps {
        bat '''
        docker tag college-event-website:latest college-event-website:%BUILD_NUMBER%
        '''
    }
}

stage('Verify Kubernetes Context') {
    steps {
        bat '''
        whoami
        kubectl config current-context
        kubectl cluster-info
        '''
    }
}

stage('Deploy to Kubernetes') {
    steps {
        bat '''
        kubectl apply -f k8s/
        kubectl set image deployment/college-event-deployment college-event-container=college-event-website:%BUILD_NUMBER%
        kubectl rollout status deployment/college-event-deployment
        '''
    }
}

stage('Verify Deployment') {
    steps {
        bat '''
        kubectl get deployments
        kubectl get pods
        kubectl get services
        '''
    }
}


        stage('Archive Build Artifacts') {
            steps {
                archiveArtifacts artifacts: 'target/**, README.md, pom.xml', fingerprint: true
            }
        }
    }

    post {
        always {
            // Cleanup Container: always tear down the smoke-test container, even if
            // the smoke test itself failed. post { always {} } runs regardless of
            // stage outcome, guaranteeing this executes.
            bat '''
                docker stop college-event-ci
                docker rm college-event-ci
                exit /b 0
            '''
            echo 'Build completed.'
        }
        success {
            echo 'Build completed successfully.'
            echo 'Kubernetes deployment completed successfully.'
        }
        failure {
            echo 'Build failed.'
            echo 'Kubernetes deployment failed.'
        }
    }
}
