// Jenkins CI pipeline for the TechnoVista college-event-website project.
//
// Scope: CI build only.
//   - Clones the repo, verifies the toolchain, runs the Maven build,
//     builds a Docker image, verifies both build outputs, and archives
//     the build artifacts.
//   - Does NOT run/stop/remove containers, deploy anywhere, or touch
//     Kubernetes/monitoring. Those belong to later phases.
//
// Agent: Windows Jenkins agent (uses `bat`, not `sh`).

pipeline {
    agent any

    options {
        timestamps()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Source') {
            steps {
                // Public repository - no Jenkins credentials required.
                git branch: 'main', url: 'https://github.com/bk9571/college-event-website.git'
            }
        }

        stage('Environment Verification') {
            steps {
                bat 'git --version'
                bat 'java -version'
                bat 'mvn -version'
                bat 'docker version'
            }
        }

        stage('Maven Build') {
            steps {
                // Fails the pipeline immediately if the Maven build fails.
                bat 'mvn clean package'
            }
        }

        stage('Verify Build Output') {
            steps {
                bat '''
                    if not exist "target\\site" (
                        echo ERROR: target\\site was not generated by the Maven build.
                        exit /b 1
                    )
                    echo target\\site verified.
                '''
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t college-event-website:latest .'
            }
        }

        stage('Verify Docker Image') {
            steps {
                bat '''
                    docker image inspect college-event-website:latest >nul 2>&1
                    if errorlevel 1 (
                        echo ERROR: Docker image college-event-website:latest was not found.
                        exit /b 1
                    )
                    echo Docker image college-event-website:latest verified.
                '''
            }
        }

        stage('Archive Build Artifacts') {
            steps {
                archiveArtifacts artifacts: 'target/**, README.md, pom.xml', fingerprint: true
            }
        }
    }

    post {
        always {
            echo 'Build completed.'
        }
        success {
            echo 'Build completed successfully.'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
