#!/bin/sh
# Phase 7B - discovers the current NodePort for college-event-service and
# (re)generates conf.d/technovista-website.cfg, then reloads Nagios.
#
# Run this from monitoring/nagios/ (or anywhere - it cd's into its own
# directory) whenever the Kubernetes Service's NodePort may have changed,
# e.g. after `kubectl apply -f k8s/` re-creates the Service.
#
# Usage: ./discover-nodeport.sh

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_FILE="$SCRIPT_DIR/conf.d/technovista-website.cfg"

NODEPORT="$(kubectl get svc college-event-service -o jsonpath='{.spec.ports[0].nodePort}' 2>/dev/null || true)"

if [ -z "$NODEPORT" ]; then
    echo "ERROR: could not discover a NodePort for Service 'college-event-service'." >&2
    echo "       Checked: kubectl get svc college-event-service -o jsonpath='{.spec.ports[0].nodePort}'" >&2
    echo "       Possible causes: kubectl not configured/reachable, the Service does not" >&2
    echo "       exist, or it is not a NodePort Service. Not writing a fake port - refusing" >&2
    echo "       to overwrite $OUT_FILE with invented data." >&2
    exit 1
fi

cat > "$OUT_FILE" <<EOF
# GENERATED by discover-nodeport.sh - do not edit by hand.
# NodePort discovered from: kubectl get svc college-event-service
# Discovered NodePort: ${NODEPORT}

define service{
    use                     generic-service
    host_name               devops-host
    service_description     TechnoVista Website Kubernetes
    check_command           check_http!-p ${NODEPORT}
    notes                   Checks the TechnoVista website via its Kubernetes NodePort, discovered dynamically (not hardcoded) at http://host.docker.internal:${NODEPORT}.
}
EOF

echo "Wrote $OUT_FILE with NodePort ${NODEPORT}."

docker exec nagios /usr/local/bin/nagios -v /opt/nagios/etc/nagios.cfg > /dev/null
echo "Nagios configuration validated OK."

docker exec nagios sv reload nagios
echo "Nagios reloaded."
