apiVersion: 1

datasources:
  - name: Graphite
    uid: graphite
    type: graphite
    access: proxy
    url: http://graphite
    isDefault: true
    editable: false
    jsonData:
      graphiteVersion: "1.1"
